User's Guide
------------

This part of the documentation, begins with some informations about Pymem,
then focuses on step-by-step instructions.

.. toctree::
    :maxdepth: 2

    foreword
    installation
    quickstart
    tutorial/index

Api Reference
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you

.. toctree::
    :maxdepth: 2

    api
    ressources

Additional Notes
----------------

Legal information, changelog are here for the interested.

.. toctree::
    :maxdepth: 2

    changelog
    license